import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Desenvolvimento e operações',
      collapsed: false,
      items: [
        'desenvolvimento-local',
        'ambientes',
        'ferramentas-api',
        'desenvolvimento-performance-api',
        'observabilidade',
        'funcionalidades-app-web-participante',
        'integracao-bi-export-sindromico',
        'operacoes-usuarios-duplicados',
      ],
    },
    {
      type: 'category',
      label: 'Arquitetura',
      items: [
        'arquitetura/configuracao-contexto-e-integracoes',
        {
          type: 'category',
          label: 'Modelagem do banco de dados',
          items: [{type: 'autogenerated', dirName: 'arquitetura/modelagem-banco-dados'}],
        },
      ],
    },
  ],
};

export default sidebars;
